//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArgosyModel
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    
    [DataContract]
    [Serializable]
    public partial class ESM_THEME_GROUP
    {
        public ESM_THEME_GROUP()
        {
            this.ESM_THEME_GROUP1 = new HashSet<ESM_THEME_GROUP>();
            this.ESM_THEME_STYLE = new HashSet<ESM_THEME_STYLE>();
        }
    	// primitiveProperties
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "THEME_GROUP_ID")]
        public int THEME_GROUP_ID { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "THEME_STRUCTURE_ID")]
        public Nullable<int> THEME_STRUCTURE_ID { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "THEME_GROUP_PARENT_ID")]
        public Nullable<int> THEME_GROUP_PARENT_ID { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "NAME")]
        public string NAME { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "CLASS")]
        public string CLASS { get; set; }
    	// navigationProperty
    
        /// <summary>
        /// 
        /// </summary>
        public virtual ESM_THEME_STRUCTURE ESM_THEME_STRUCTURE { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public virtual ICollection<ESM_THEME_GROUP> ESM_THEME_GROUP1 { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public virtual ESM_THEME_GROUP ESM_THEME_GROUP2 { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public virtual ICollection<ESM_THEME_STYLE> ESM_THEME_STYLE { get; set; }
    }
}
