//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArgosyModel
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    
    [DataContract]
    [Serializable]
    public partial class ESM_THEME_OPTION
    {
    	// primitiveProperties
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "THEME_OPTION_ID")]
        public int THEME_OPTION_ID { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "THEME_STYLE_ID")]
        public int THEME_STYLE_ID { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "VALUE")]
        public string VALUE { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "TEXT")]
        public string TEXT { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "IS_SELECTED")]
        public bool IS_SELECTED { get; set; }
    	// navigationProperty
    
        /// <summary>
        /// 
        /// </summary>
        public virtual ESM_THEME_STYLE ESM_THEME_STYLE { get; set; }
    }
}
