//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArgosyModel
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    
    [DataContract]
    [Serializable]
    public partial class ESM_THEME_STYLE
    {
        public ESM_THEME_STYLE()
        {
            this.ESM_THEME_OPTION = new HashSet<ESM_THEME_OPTION>();
        }
    	// primitiveProperties
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "THEME_STYLE_ID")]
        public int THEME_STYLE_ID { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "THEME_GROUP_ID")]
        public int THEME_GROUP_ID { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "THEME_ID")]
        public int THEME_ID { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "DISPLAY_NAME")]
        public string DISPLAY_NAME { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "NAME")]
        public string NAME { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "VALUE")]
        public string VALUE { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "SELECTOR")]
        public string SELECTOR { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "ROLE")]
        public string ROLE { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "IS_PRIMARY")]
        public bool IS_PRIMARY { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "IS_SECONDARY")]
        public bool IS_SECONDARY { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "IS_TERTIARY")]
        public bool IS_TERTIARY { get; set; }
    	// navigationProperty
    
        /// <summary>
        /// 
        /// </summary>
        public virtual ESM_THEME_GROUP ESM_THEME_GROUP { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public virtual ICollection<ESM_THEME_OPTION> ESM_THEME_OPTION { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public virtual ESM_THEME ESM_THEME { get; set; }
    }
}
