//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArgosyModel
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    
    [DataContract]
    [Serializable]
    public partial class ESM_COMPANY
    {
        public ESM_COMPANY()
        {
            //this.ASSET_ALLOWED_EXTENSION = new HashSet<ASSET_ALLOWED_EXTENSION>();
            //this.ASSET_GROUP = new HashSet<ASSET_GROUP>();
            //this.ASSET_INPUT_OUTPUT_FORMAT = new HashSet<ASSET_INPUT_OUTPUT_FORMAT>();
            //this.ASSET_METADATA_TYPE = new HashSet<ASSET_METADATA_TYPE>();
            //this.ASSET_ROLE = new HashSet<ASSET_ROLE>();
            //this.ASSET_TAG = new HashSet<ASSET_TAG>();
            //this.ESM_ACCOUNTING_UNIT = new HashSet<ESM_ACCOUNTING_UNIT>();
            //this.ESM_APPROVAL_ROUTING = new HashSet<ESM_APPROVAL_ROUTING>();
            //this.ESM_APPROVAL_WORKFLOW = new HashSet<ESM_APPROVAL_WORKFLOW>();
            //this.ESM_ASSET_LIST = new HashSet<ESM_ASSET_LIST>();
            //this.ESM_ASSET_UPLOAD = new HashSet<ESM_ASSET_UPLOAD>();
            //this.ESM_ASSETS_ALLOWED = new HashSet<ESM_ASSETS_ALLOWED>();
            //this.ESM_COMMUNICATION = new HashSet<ESM_COMMUNICATION>();
            //this.ESM_COMP_ADDRESS = new HashSet<ESM_COMP_ADDRESS>();
            //this.ESM_COMP_ADDRESS1 = new HashSet<ESM_COMP_ADDRESS>();
            //this.ESM_COMP_PRICELIST = new HashSet<ESM_COMP_PRICELIST>();
            //this.ESM_COMP_USER_DOLLAR_BUCKET = new HashSet<ESM_COMP_USER_DOLLAR_BUCKET>();
            //this.ESM_COMP_USERGROUP = new HashSet<ESM_COMP_USERGROUP>();
            //this.ESM_COMP_USERS = new HashSet<ESM_COMP_USERS>();
            //this.ESM_COMPANY_DOMAIN = new HashSet<ESM_COMPANY_DOMAIN>();
            //this.ESM_COMPANY_FILTER = new HashSet<ESM_COMPANY_FILTER>();
            //this.ESM_COMPANY_FLAT_HANDLING_RATE = new HashSet<ESM_COMPANY_FLAT_HANDLING_RATE>();
            //this.ESM_COMPANY_LINK = new HashSet<ESM_COMPANY_LINK>();
            //this.ESM_COMPANY_PAGE = new HashSet<ESM_COMPANY_PAGE>();
            //this.ESM_COMPANY_TAXABLE_STATES = new HashSet<ESM_COMPANY_TAXABLE_STATES>();
            //this.ESM_COMPCARRIER = new HashSet<ESM_COMPCARRIER>();
            //this.ESM_COMPCUSTOM = new HashSet<ESM_COMPCUSTOM>();
            //this.ESM_COMPGROUP = new HashSet<ESM_COMPGROUP>();
            //this.ESM_CONSUMER_COMPANY = new HashSet<ESM_CONSUMER_COMPANY>();
            //this.ESM_CUSTOM_EMAIL_MAP = new HashSet<ESM_CUSTOM_EMAIL_MAP>();
            //this.ESM_CXML_CONFIG = new HashSet<ESM_CXML_CONFIG>();
            //this.ESM_DASH_COMPANY_WIDGETS = new HashSet<ESM_DASH_COMPANY_WIDGETS>();
            //this.ESM_DASH = new HashSet<ESM_DASH>();
            //this.ESM_DATA_PROVIDER_CONFIG = new HashSet<ESM_DATA_PROVIDER_CONFIG>();
            //this.ESM_DISCOUNT = new HashSet<ESM_DISCOUNT>();
            //this.ESM_GLOBAL_FORMS = new HashSet<ESM_GLOBAL_FORMS>();
            //this.ESM_GLOBALSTOREFRONT_DATA = new HashSet<ESM_GLOBALSTOREFRONT_DATA>();
            //this.ESM_HD_TICKET = new HashSet<ESM_HD_TICKET>();
            //this.ESM_IMPORT_PROCESSING = new HashSet<ESM_IMPORT_PROCESSING>();
            //this.ESM_LOCALIZATION_MAP = new HashSet<ESM_LOCALIZATION_MAP>();
            //this.ESM_MAILING_LIST_CORP = new HashSet<ESM_MAILING_LIST_CORP>();
            //this.ESM_MAILING_LIST_FILTER = new HashSet<ESM_MAILING_LIST_FILTER>();
            //this.ESM_ORDER_LIMIT = new HashSet<ESM_ORDER_LIMIT>();
            //this.ESM_PART_BUYER_GROUP = new HashSet<ESM_PART_BUYER_GROUP>();
            //this.ESM_PART = new HashSet<ESM_PART>();
            //this.ESM_PART_PRICE_AGGREGATE = new HashSet<ESM_PART_PRICE_AGGREGATE>();
            //this.ESM_PROJECTS = new HashSet<ESM_PROJECTS>();
            //this.ESM_PROMO_COMPANY = new HashSet<ESM_PROMO_COMPANY>();
            //this.ESM_PROMOTIONS = new HashSet<ESM_PROMOTIONS>();
            //this.ESM_PURCHASE_ORDERS = new HashSet<ESM_PURCHASE_ORDERS>();
            //this.ESM_REP_SLICE_SNAPSHOT = new HashSet<ESM_REP_SLICE_SNAPSHOT>();
            //this.ESM_REPNEW_REPORT_SCHEDULER = new HashSet<ESM_REPNEW_REPORT_SCHEDULER>();
            //this.ESM_REPNEW_VIEWS = new HashSet<ESM_REPNEW_VIEWS>();
            //this.ESM_RET_PROJECT = new HashSet<ESM_RET_PROJECT>();
            //this.ESM_RET_USER_GROUP = new HashSet<ESM_RET_USER_GROUP>();
            //this.ESM_RMA = new HashSet<ESM_RMA>();
            //this.ESM_SERVICE_SECURITY = new HashSet<ESM_SERVICE_SECURITY>();
            //this.ESM_SOFT_PROOFING_TRANSACTION_LOG = new HashSet<ESM_SOFT_PROOFING_TRANSACTION_LOG>();
            //this.ESM_TEMPLATE = new HashSet<ESM_TEMPLATE>();
            //this.ESM_THEME1 = new HashSet<ESM_THEME>();
            //this.ESM_UI_CUSTOM_TEXT = new HashSet<ESM_UI_CUSTOM_TEXT>();
            //this.SYS_ALERT_OPTIONS = new HashSet<SYS_ALERT_OPTIONS>();
            //this.SYS_TASK = new HashSet<SYS_TASK>();
            //this.SYS_TASK_ORDER_IMPORT = new HashSet<SYS_TASK_ORDER_IMPORT>();
            //this.ESM_COMPGROUP1 = new HashSet<ESM_COMPGROUP>();
            //this.ESM_ORDERS = new HashSet<ESM_ORDERS>();
            //this.ESM_COMPANY_PRICEBREAK_COST_FIELDS = new HashSet<ESM_COMPANY_PRICEBREAK_COST_FIELDS>();
        }
    	// primitiveProperties
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "COMPANY_ID")]
        public int COMPANY_ID { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "COMP_CONTACT_ID")]
        public Nullable<int> COMP_CONTACT_ID { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "PARTNER_ID")]
        [Obsolete("PARTNER_ID should no longer be used in Argosy")]
        public Nullable<int> PARTNER_ID { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "IMAGE_ID")]
        [Obsolete("IMAGE_ID should no longer be used in Argosy")]
        public Nullable<int> IMAGE_ID { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "THEME_ID")]
        public Nullable<int> THEME_ID { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "SITE_ID")]
        public int SITE_ID { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "DEFAULT_USER_ID")]
        public int DEFAULT_USER_ID { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "WAREHOUSE_ID")]
        public Nullable<int> WAREHOUSE_ID { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "COMPANY_NAME")]
        public string COMPANY_NAME { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "STORE_USER_ID")]
        public Nullable<int> STORE_USER_ID { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "DEFAULT_SKIN_ID")]
        public Nullable<int> DEFAULT_SKIN_ID { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "STORE_GUID")]
        public string STORE_GUID { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "COMPANY_URL")]
        public string COMPANY_URL { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "CUSTOM_LOGINPATH")]
        public string CUSTOM_LOGINPATH { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "CUSTOM_PACKLIST_PATH")]
        public string CUSTOM_PACKLIST_PATH { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "REPORT_CODE")]
        [Obsolete("REPORT_CODE should no longer be used in Argosy")]
        public string REPORT_CODE { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "FILENAME")]
        public string FILENAME { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "LEAD_TIME")]
        public int LEAD_TIME { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "CUSTOM_COUNT")]
        public int CUSTOM_COUNT { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "PREPRESS_CHARGE")]
        public decimal PREPRESS_CHARGE { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "ORDER_CHARGE")]
        public decimal ORDER_CHARGE { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "LINE_CHARGE")]
        public decimal LINE_CHARGE { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "EACH_CHARGE")]
        public decimal EACH_CHARGE { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "MAX_ORDER_AMOUNT")]
        public decimal MAX_ORDER_AMOUNT { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "MIN_ORDER_AMT")]
        public decimal MIN_ORDER_AMT { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "EDELIVERY_PRICE")]
        public decimal EDELIVERY_PRICE { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "ECOMMERCE_ACCESS_CODE")]
        public string ECOMMERCE_ACCESS_CODE { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "LANDING_PAGE_HTML")]
        public string LANDING_PAGE_HTML { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "LANDING_PAGE_SETTING")]
        public string LANDING_PAGE_SETTING { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "FTP_SITE")]
        [Obsolete("FTP_SITE should no longer be used in Argosy")]
        public string FTP_SITE { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "FTP_USERNAME")]
        [Obsolete("FTP_USERNAME should no longer be used in Argosy")]
        public string FTP_USERNAME { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "FTP_PASSWORD")]
        [Obsolete("FTP_PASSWORD should no longer be used in Argosy")]
        public string FTP_PASSWORD { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "USER_DEFAULT_PART_IMAGE_MAX")]
        [Obsolete("USER_DEFAULT_PART_IMAGE_MAX should no longer be used in Argosy")]
        public long USER_DEFAULT_PART_IMAGE_MAX { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "USER_DEFAULT_PART_IMAGE_MIN")]
        [Obsolete("USER_DEFAULT_PART_IMAGE_MIN should no longer be used in Argosy")]
        public long USER_DEFAULT_PART_IMAGE_MIN { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "CYCLE")]
        [Obsolete("CYCLE should no longer be used in Argosy")]
        public string CYCLE { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "ORDER_NUMBER_SUFIX")]
        [Obsolete("ORDER_NUMBER_SUFIX should no longer be used in Argosy")]
        public string ORDER_NUMBER_SUFIX { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "ORDER_MID_NUM")]
        public Nullable<int> ORDER_MID_NUM { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "ORDER_NUMBER_PREFIX")]
        public string ORDER_NUMBER_PREFIX { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "TIME_EXPEDITE")]
        public string TIME_EXPEDITE { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "TIME_CUTOFF")]
        public string TIME_CUTOFF { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "VERSION")]
        public int VERSION { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "PAYMENT_CREDIT_CARD_IS_ALLOWED")]
        public bool PAYMENT_CREDIT_CARD_IS_ALLOWED { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "PAYMENT_ECHECK_IS_ALLOWED")]
        [Obsolete("PAYMENT_ECHECK_IS_ALLOWED should no longer be used in Argosy")]
        public bool PAYMENT_ECHECK_IS_ALLOWED { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "PAYMENT_PO_IS_ALLOWED")]
        public bool PAYMENT_PO_IS_ALLOWED { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "PAYMENT_BILL_LATER_IS_ALLOWED")]
        public bool PAYMENT_BILL_LATER_IS_ALLOWED { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "DIRECT_MAIL_SPENDING_MINIMUM")]
        public decimal DIRECT_MAIL_SPENDING_MINIMUM { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "ISACTIVE")]
        public bool ISACTIVE { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "IS_TAXABLE")]
        public bool IS_TAXABLE { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "IS_FREIGHT_ONLY_BILLING")]
        public bool IS_FREIGHT_ONLY_BILLING { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "IS_ECOMMERCE_CODE_REQUIRED")]
        public bool IS_ECOMMERCE_CODE_REQUIRED { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "ALLOW_PART_RESTRICTION")]
        [Obsolete("ALLOW_PART_RESTRICTION should no longer be used in Argosy")]
        public bool ALLOW_PART_RESTRICTION { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "FLAG_REQUIRE_PO")]
        public bool FLAG_REQUIRE_PO { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "FLAG_APPROVALS")]
        [Obsolete("FLAG_APPROVALS should no longer be used in Argosy")]
        public string FLAG_APPROVALS { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "FLAG_SPENDING_LIMITS")]
        [Obsolete("FLAG_SPENDING_LIMITS should no longer be used in Argosy")]
        public string FLAG_SPENDING_LIMITS { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "FLAG_ADDRESS_EDIT_ST")]
        [Obsolete("FLAG_ADDRESS_EDIT_ST should no longer be used in Argosy")]
        public string FLAG_ADDRESS_EDIT_ST { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "FLAG_SHOW_PRICE")]
        public string FLAG_SHOW_PRICE { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "FLAG_SHOW_INV")]
        public string FLAG_SHOW_INV { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "FLAG_PARTIAL_SHIP")]
        public string FLAG_PARTIAL_SHIP { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "FLAG_ORDER_UNITS")]
        [Obsolete("FLAG_ORDER_UNITS should no longer be used in Argosy")]
        public string FLAG_ORDER_UNITS { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "FLAG_ORDER_QTY_MAX")]
        public string FLAG_ORDER_QTY_MAX { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "FLAG_EMAIL_HTML")]
        [Obsolete("FLAG_EMAIL_HTML should no longer be used in Argosy")]
        public string FLAG_EMAIL_HTML { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "FLAG_GEN_XML")]
        [Obsolete("FLAG_GEN_XML should no longer be used in Argosy")]
        public string FLAG_GEN_XML { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "FLAG_INCLUDE_CUSTOM_FIELDS")]
        public string FLAG_INCLUDE_CUSTOM_FIELDS { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "FLAG_VERIFY_ADDRESS")]
        public bool FLAG_VERIFY_ADDRESS { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "FLAG_AUTO_DEPLETE")]
        public string FLAG_AUTO_DEPLETE { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "FLAG_COLAB_TOOL")]
        public string FLAG_COLAB_TOOL { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "FLAG_CUSTOMIZE")]
        [Obsolete("FLAG_CUSTOMIZE should no longer be used in Argosy")]
        public string FLAG_CUSTOMIZE { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "FLAG_CARRIER")]
        [Obsolete("FLAG_CARRIER should no longer be used in Argosy")]
        public string FLAG_CARRIER { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "FLAG_ORDER_STATUS")]
        public string FLAG_ORDER_STATUS { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "FLAG_SHIPPING_COSTS")]
        public string FLAG_SHIPPING_COSTS { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "FLAG_DESIRED_SHIP_DATE")]
        public string FLAG_DESIRED_SHIP_DATE { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "FLAG_ESTIMATE_SHIP_DATE")]
        public string FLAG_ESTIMATE_SHIP_DATE { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "FLAG_BROWSE_DISPLAY")]
        [Obsolete("FLAG_BROWSE_DISPLAY should no longer be used in Argosy")]
        public string FLAG_BROWSE_DISPLAY { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "FLAG_CC_REQUIRED")]
        [Obsolete("FLAG_CC_REQUIRED should no longer be used in Argosy")]
        public string FLAG_CC_REQUIRED { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "FLAG_USE_PRECLOSE")]
        [Obsolete("FLAG_USE_PRECLOSE should no longer be used in Argosy")]
        public string FLAG_USE_PRECLOSE { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "FLAG_CC_PROCESS")]
        [Obsolete("FLAG_CC_PROCESS should no longer be used in Argosy")]
        public string FLAG_CC_PROCESS { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "FLAG_SHOW_PART_THUMBS")]
        [Obsolete("FLAG_SHOW_PART_THUMBS should no longer be used in Argosy")]
        public string FLAG_SHOW_PART_THUMBS { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "FLAG_ALLOW_EDIT_GROUP_TITLES")]
        [Obsolete("FLAG_ALLOW_EDIT_GROUP_TITLES should no longer be used in Argosy")]
        public string FLAG_ALLOW_EDIT_GROUP_TITLES { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "FLAG_ALLOW_GEOROUT")]
        [Obsolete("FLAG_ALLOW_GEOROUT should no longer be used in Argosy")]
        public bool FLAG_ALLOW_GEOROUT { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "FLAG_SHOW_NEW_PRODUCTS_GROUP")]
        public string FLAG_SHOW_NEW_PRODUCTS_GROUP { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "FLAG_FREE_CF_PARTS")]
        [Obsolete("FLAG_FREE_CF_PARTS should no longer be used in Argosy")]
        public string FLAG_FREE_CF_PARTS { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "FLAG_FAST_PICKPACK")]
        public string FLAG_FAST_PICKPACK { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "FLAG_FAST_PICKPACK_DEFAULT")]
        public string FLAG_FAST_PICKPACK_DEFAULT { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "FLAG_ALLOW_SPLIT_SHIPPING")]
        public string FLAG_ALLOW_SPLIT_SHIPPING { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "FLAG_ALLOW_CONSOLIDATE_ORDERS")]
        public string FLAG_ALLOW_CONSOLIDATE_ORDERS { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "FLAG_CONSUMER_MODULE")]
        public bool FLAG_CONSUMER_MODULE { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "FLAG_ASSET_MODULE")]
        public bool FLAG_ASSET_MODULE { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "FLAG_ASSET_RESTRICTED")]
        public bool FLAG_ASSET_RESTRICTED { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "FLAG_ALLOW_LIST_PURCHASES")]
        public string FLAG_ALLOW_LIST_PURCHASES { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "FLAG_ALLOW_UPLOAD_LIST")]
        public bool FLAG_ALLOW_UPLOAD_LIST { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "FLAG_ALLOW_EXISTING_LIST")]
        public bool FLAG_ALLOW_EXISTING_LIST { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "FLAG_ALLOW_BUILD_LIST")]
        [Obsolete("FLAG_ALLOW_BUILD_LIST should no longer be used in Argosy")]
        public bool FLAG_ALLOW_BUILD_LIST { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "FLAG_USERS_CAN_EDIT_PERSONAL_INFORMATION")]
        public bool FLAG_USERS_CAN_EDIT_PERSONAL_INFORMATION { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "FLAG_NEEDS_INVENTORY_APPROVAL")]
        public bool FLAG_NEEDS_INVENTORY_APPROVAL { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "FLAG_HAS_PART_LIMITS")]
        public bool FLAG_HAS_PART_LIMITS { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "FLAG_REQUIRE_SIGNATURE")]
        [Obsolete("FLAG_REQUIRE_SIGNATURE should no longer be used in Argosy")]
        public bool FLAG_REQUIRE_SIGNATURE { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "FLAG_IS_SYSTEM_DOLLAR")]
        public bool FLAG_IS_SYSTEM_DOLLAR { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "FLAG_ECOMMERCE_CUSTOMER")]
        public bool FLAG_ECOMMERCE_CUSTOMER { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "FLAG_SHOW_PART_CATEGORY_THUMBS")]
        [Obsolete("FLAG_SHOW_PART_CATEGORY_THUMBS should no longer be used in Argosy")]
        public string FLAG_SHOW_PART_CATEGORY_THUMBS { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "FLAG_SHOW_CORPORATE_LIST")]
        public bool FLAG_SHOW_CORPORATE_LIST { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "FLAG_ALLOW_EDIT_PRICE")]
        [Obsolete("FLAG_ALLOW_EDIT_PRICE should no longer be used in Argosy")]
        public bool FLAG_ALLOW_EDIT_PRICE { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "FLAG_ALLOW_MULTI_PRICE_LIST")]
        public bool FLAG_ALLOW_MULTI_PRICE_LIST { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "FLAG_ALLOW_PARTIAL_WAVE_FOR_KITS")]
        public bool FLAG_ALLOW_PARTIAL_WAVE_FOR_KITS { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "FLAG_STOP_ORDERS")]
        public string FLAG_STOP_ORDERS { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "FLAG_REQUIRE_CARTONS")]
        public bool FLAG_REQUIRE_CARTONS { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "FLAG_USER_CAN_CHANGE_SKIN")]
        public Nullable<bool> FLAG_USER_CAN_CHANGE_SKIN { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "FLAG_ALLOW_PROMO_CODES")]
        public bool FLAG_ALLOW_PROMO_CODES { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "FLAG_SHOW_CROSS_SALE")]
        public bool FLAG_SHOW_CROSS_SALE { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "FLAG_APPROVAL_ON_ALL_ORDERS")]
        public bool FLAG_APPROVAL_ON_ALL_ORDERS { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "FLAG_APPROVAL_ON_AU")]
        public bool FLAG_APPROVAL_ON_AU { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "FLAG_APPROVAL_ON_PART_THRESHHOLD")]
        public bool FLAG_APPROVAL_ON_PART_THRESHHOLD { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "FLAG_APPROVAL_ON_SPENDING_LIMIT")]
        public bool FLAG_APPROVAL_ON_SPENDING_LIMIT { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "FLAG_BYPASS_APPROVAL_ON_CC")]
        public bool FLAG_BYPASS_APPROVAL_ON_CC { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "FLAG_APPROVAL_WORK_FLOW_TYPE")]
        public string FLAG_APPROVAL_WORK_FLOW_TYPE { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "FLAG_ALLOW_WEEKEND_SHIP")]
        public string FLAG_ALLOW_WEEKEND_SHIP { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "FLAG_SHOW_HIGH_RES_PROOF")]
        public bool FLAG_SHOW_HIGH_RES_PROOF { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "SHIPPING_DAY")]
        public string SHIPPING_DAY { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "TIME_INTERVAL")]
        public string TIME_INTERVAL { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "CONSUMER_VIEW_RIGHTS")]
        public string CONSUMER_VIEW_RIGHTS { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "DATECREATED")]
        public Nullable<System.DateTime> DATECREATED { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "CREATEDBY")]
        public int CREATEDBY { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "DATEMODIFIED")]
        public Nullable<System.DateTime> DATEMODIFIED { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "MODIFIEDBY")]
        public int MODIFIEDBY { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "RETAIL_SIGNATURE_NUMBER")]
        public int RETAIL_SIGNATURE_NUMBER { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "IS_TEST_CUSTOMER")]
        public bool IS_TEST_CUSTOMER { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "FLAG_ALLOW_REGISTRATION")]
        public bool FLAG_ALLOW_REGISTRATION { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "FLAG_SALES_TAX_TYPE")]
        public int FLAG_SALES_TAX_TYPE { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "FLAT_SALES_TAX_RATE")]
        public Nullable<decimal> FLAT_SALES_TAX_RATE { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "FLAG_CREATE_PAY_REC_FOR_ALL")]
        public bool FLAG_CREATE_PAY_REC_FOR_ALL { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "COMPANY_GUID")]
        public System.Guid COMPANY_GUID { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "FLAG_SAVE_ACCOUNTING_UNIT_TO_ORDERLINE")]
        public bool FLAG_SAVE_ACCOUNTING_UNIT_TO_ORDERLINE { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "FLAG_CXML_PUNCHOUT")]
        public bool FLAG_CXML_PUNCHOUT { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "RETURN_URL")]
        public string RETURN_URL { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "FLAG_LOCK_PROOF_NAME")]
        public bool FLAG_LOCK_PROOF_NAME { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "FLAG_APPROVAL_OVERRIDE_PART_LIMIT")]
        public bool FLAG_APPROVAL_OVERRIDE_PART_LIMIT { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "FLAG_APPROVAL_ON_ORDERS_PER_DAY")]
        public bool FLAG_APPROVAL_ON_ORDERS_PER_DAY { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "FLAG_SHOW_ALERT_IF_APPROVAL_TRIGGERED")]
        public bool FLAG_SHOW_ALERT_IF_APPROVAL_TRIGGERED { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "WHITE_LABEL")]
        public string WHITE_LABEL { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "WHITE_LABEL_SITE_LOGO")]
        public string WHITE_LABEL_SITE_LOGO { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "WHITE_LABEL_LOADING_IMAGE")]
        public string WHITE_LABEL_LOADING_IMAGE { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "WHITE_LABEL_SITE_ICON")]
        public string WHITE_LABEL_SITE_ICON { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "FLAG_LOCK_ADDRESS")]
        public bool FLAG_LOCK_ADDRESS { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "EXTERNAL_ID_1")]
        public string EXTERNAL_ID_1 { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "EXTERNAL_ID_2")]
        public string EXTERNAL_ID_2 { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "SITE_GATEWAY_ID")]
        public Nullable<int> SITE_GATEWAY_ID { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "PAYMENT_CO_OP_ONLY")]
        public bool PAYMENT_CO_OP_ONLY { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "FULFILL_MIN_COST")]
        public Nullable<decimal> FULFILL_MIN_COST { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "FULFILL_MIN_ORDER_COST")]
        public Nullable<decimal> FULFILL_MIN_ORDER_COST { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "ORDER_PAYMENT_TYPE")]
        public Nullable<int> ORDER_PAYMENT_TYPE { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "EXPIRING_SOON_DAYS")]
        public int EXPIRING_SOON_DAYS { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "NEW_SHOWS_CONTROL_FIELD")]
        public int NEW_SHOWS_CONTROL_FIELD { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "NEW_SHOWS_FOR_DAYS")]
        public int NEW_SHOWS_FOR_DAYS { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "UPDATED_SHOWS_CONTROL_FIELD")]
        public int UPDATED_SHOWS_CONTROL_FIELD { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "UPDATED_SHOWS_FOR_DAYS")]
        public int UPDATED_SHOWS_FOR_DAYS { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "FLAG_VIEW_SKU_ON_BROWSE")]
        public bool FLAG_VIEW_SKU_ON_BROWSE { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "FLAG_ALWAYS_REQUIRE_SHIPPING_ADDRESS")]
        public bool FLAG_ALWAYS_REQUIRE_SHIPPING_ADDRESS { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "FLAG_ALWAYS_REQUIRE_BILLING_ADDRESS")]
        public bool FLAG_ALWAYS_REQUIRE_BILLING_ADDRESS { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "IS_APPROVAL_WORKFLOW")]
        public bool IS_APPROVAL_WORKFLOW { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "FLAG_LOCK_ADDRESS_BT")]
        public bool FLAG_LOCK_ADDRESS_BT { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "FLAG_ALLOW_SAVE_CC")]
        public bool FLAG_ALLOW_SAVE_CC { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "SHOW_PASSWORD_ON_WELCOME_EMAIL")]
        public bool SHOW_PASSWORD_ON_WELCOME_EMAIL { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "INVOICE_FEE")]
        public Nullable<decimal> INVOICE_FEE { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "FLAG_SHOW_INVOICE_FEE")]
        public bool FLAG_SHOW_INVOICE_FEE { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "FLAG_ALLOW_USER_MANAGEMENT")]
        public bool FLAG_ALLOW_USER_MANAGEMENT { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "FLAG_DEFAULT_SHIPPING")]
        public Nullable<bool> FLAG_DEFAULT_SHIPPING { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "FLAG_DEFAULT_BILLING")]
        public Nullable<bool> FLAG_DEFAULT_BILLING { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "PORTAL_DISPLAY_JSON")]
        public string PORTAL_DISPLAY_JSON { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "TAX_ENTITY_ID")]
        public string TAX_ENTITY_ID { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "IS_SHIPPING_HIDDEN")]
        public bool IS_SHIPPING_HIDDEN { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "FLAG_OPEN_PORTAL_COMPANY_NAME_REQUIRED")]
        public bool FLAG_OPEN_PORTAL_COMPANY_NAME_REQUIRED { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "FLAG_SHOW_ADDITIONAL_PART_DETAILS")]
        public bool FLAG_SHOW_ADDITIONAL_PART_DETAILS { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "FLAG_ALLOW_ADDITIONAL_ORDER_FILES")]
        public bool FLAG_ALLOW_ADDITIONAL_ORDER_FILES { get; set; }
    	// navigationProperty
    
        /// <summary>
        /// 
        /// </summary>
        //public virtual ICollection<ASSET_ALLOWED_EXTENSION> ASSET_ALLOWED_EXTENSION { get; set; }
        ///// <summary>
        ///// 
        ///// </summary>
        //public virtual ICollection<ASSET_GROUP> ASSET_GROUP { get; set; }
        ///// <summary>
        ///// 
        ///// </summary>
        //public virtual ICollection<ASSET_INPUT_OUTPUT_FORMAT> ASSET_INPUT_OUTPUT_FORMAT { get; set; }
        ///// <summary>
        ///// 
        ///// </summary>
        //public virtual ICollection<ASSET_METADATA_TYPE> ASSET_METADATA_TYPE { get; set; }
        ///// <summary>
        ///// 
        ///// </summary>
        //public virtual ICollection<ASSET_ROLE> ASSET_ROLE { get; set; }
        ///// <summary>
        ///// 
        ///// </summary>
        //public virtual ICollection<ASSET_TAG> ASSET_TAG { get; set; }
        ///// <summary>
        ///// 
        ///// </summary>
        //public virtual ICollection<ESM_ACCOUNTING_UNIT> ESM_ACCOUNTING_UNIT { get; set; }
        ///// <summary>
        ///// 
        ///// </summary>
        //public virtual ICollection<ESM_APPROVAL_ROUTING> ESM_APPROVAL_ROUTING { get; set; }
        ///// <summary>
        ///// 
        ///// </summary>
        //public virtual ICollection<ESM_APPROVAL_WORKFLOW> ESM_APPROVAL_WORKFLOW { get; set; }
        ///// <summary>
        ///// 
        ///// </summary>
        //public virtual ICollection<ESM_ASSET_LIST> ESM_ASSET_LIST { get; set; }
        ///// <summary>
        ///// 
        ///// </summary>
        //public virtual ICollection<ESM_ASSET_UPLOAD> ESM_ASSET_UPLOAD { get; set; }
        ///// <summary>
        ///// 
        ///// </summary>
        //public virtual ICollection<ESM_ASSETS_ALLOWED> ESM_ASSETS_ALLOWED { get; set; }
        ///// <summary>
        ///// 
        ///// </summary>
        //public virtual ICollection<ESM_COMMUNICATION> ESM_COMMUNICATION { get; set; }
        ///// <summary>
        ///// 
        ///// </summary>
        //public virtual ICollection<ESM_COMP_ADDRESS> ESM_COMP_ADDRESS { get; set; }
        ///// <summary>
        ///// 
        ///// </summary>
        //public virtual ICollection<ESM_COMP_ADDRESS> ESM_COMP_ADDRESS1 { get; set; }
        ///// <summary>
        ///// 
        ///// </summary>
        //public virtual ESM_COMP_CONTACT ESM_COMP_CONTACT { get; set; }
        ///// <summary>
        ///// 
        ///// </summary>
        //public virtual ICollection<ESM_COMP_PRICELIST> ESM_COMP_PRICELIST { get; set; }
        ///// <summary>
        ///// 
        ///// </summary>
        //public virtual ICollection<ESM_COMP_USER_DOLLAR_BUCKET> ESM_COMP_USER_DOLLAR_BUCKET { get; set; }
        ///// <summary>
        ///// 
        ///// </summary>
        //public virtual ICollection<ESM_COMP_USERGROUP> ESM_COMP_USERGROUP { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public virtual ICollection<ESM_COMP_USERS> ESM_COMP_USERS { get; set; }
        /// <summary>
        /// 
        /// </summary>
        //public virtual ICollection<ESM_COMPANY_DOMAIN> ESM_COMPANY_DOMAIN { get; set; }
        ///// <summary>
        ///// 
        ///// </summary>
        //public virtual ESM_SITE ESM_SITE { get; set; }
        ///// <summary>
        ///// 
        ///// </summary>
        //public virtual ESM_SITE_GATEWAY ESM_SITE_GATEWAY { get; set; }
        ///// <summary>
        ///// 
        ///// </summary>
        //public virtual ESM_SITE ESM_SITE1 { get; set; }
        ///// <summary>
        ///// 
        ///// </summary>
        //public virtual ESM_SKIN ESM_SKIN { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public virtual ESM_THEME ESM_THEME { get; set; }
        /// <summary>
        /// 
        /// </summary>
        //public virtual ESM_WAREHOUSE ESM_WAREHOUSE { get; set; }
        ///// <summary>
        ///// 
        ///// </summary>
        //public virtual ICollection<ESM_COMPANY_FILTER> ESM_COMPANY_FILTER { get; set; }
        ///// <summary>
        ///// 
        ///// </summary>
        //public virtual ICollection<ESM_COMPANY_FLAT_HANDLING_RATE> ESM_COMPANY_FLAT_HANDLING_RATE { get; set; }
        ///// <summary>
        ///// 
        ///// </summary>
        //public virtual ICollection<ESM_COMPANY_LINK> ESM_COMPANY_LINK { get; set; }
        ///// <summary>
        ///// 
        ///// </summary>
        //public virtual ICollection<ESM_COMPANY_PAGE> ESM_COMPANY_PAGE { get; set; }
        ///// <summary>
        ///// 
        ///// </summary>
        //public virtual ICollection<ESM_COMPANY_TAXABLE_STATES> ESM_COMPANY_TAXABLE_STATES { get; set; }
        ///// <summary>
        ///// 
        ///// </summary>
        //public virtual ICollection<ESM_COMPCARRIER> ESM_COMPCARRIER { get; set; }
        ///// <summary>
        ///// 
        ///// </summary>
        //public virtual ICollection<ESM_COMPCUSTOM> ESM_COMPCUSTOM { get; set; }
        ///// <summary>
        ///// 
        ///// </summary>
        //public virtual ICollection<ESM_COMPGROUP> ESM_COMPGROUP { get; set; }
        ///// <summary>
        ///// 
        ///// </summary>
        //public virtual ICollection<ESM_CONSUMER_COMPANY> ESM_CONSUMER_COMPANY { get; set; }
        ///// <summary>
        ///// 
        ///// </summary>
        //public virtual ICollection<ESM_CUSTOM_EMAIL_MAP> ESM_CUSTOM_EMAIL_MAP { get; set; }
        ///// <summary>
        ///// 
        ///// </summary>
        //public virtual ICollection<ESM_CXML_CONFIG> ESM_CXML_CONFIG { get; set; }
        ///// <summary>
        ///// 
        ///// </summary>
        //public virtual ICollection<ESM_DASH_COMPANY_WIDGETS> ESM_DASH_COMPANY_WIDGETS { get; set; }
        ///// <summary>
        ///// 
        ///// </summary>
        //public virtual ICollection<ESM_DASH> ESM_DASH { get; set; }
        ///// <summary>
        ///// 
        ///// </summary>
        //public virtual ICollection<ESM_DATA_PROVIDER_CONFIG> ESM_DATA_PROVIDER_CONFIG { get; set; }
        ///// <summary>
        ///// 
        ///// </summary>
        //public virtual ICollection<ESM_DISCOUNT> ESM_DISCOUNT { get; set; }
        ///// <summary>
        ///// 
        ///// </summary>
        //public virtual ICollection<ESM_GLOBAL_FORMS> ESM_GLOBAL_FORMS { get; set; }
        ///// <summary>
        ///// 
        ///// </summary>
        //public virtual ICollection<ESM_GLOBALSTOREFRONT_DATA> ESM_GLOBALSTOREFRONT_DATA { get; set; }
        ///// <summary>
        ///// 
        ///// </summary>
        //public virtual ICollection<ESM_HD_TICKET> ESM_HD_TICKET { get; set; }
        ///// <summary>
        ///// 
        ///// </summary>
        //public virtual ICollection<ESM_IMPORT_PROCESSING> ESM_IMPORT_PROCESSING { get; set; }
        ///// <summary>
        ///// 
        ///// </summary>
        //public virtual ICollection<ESM_LOCALIZATION_MAP> ESM_LOCALIZATION_MAP { get; set; }
        ///// <summary>
        ///// 
        ///// </summary>
        //public virtual ICollection<ESM_MAILING_LIST_CORP> ESM_MAILING_LIST_CORP { get; set; }
        ///// <summary>
        ///// 
        ///// </summary>
        //public virtual ICollection<ESM_MAILING_LIST_FILTER> ESM_MAILING_LIST_FILTER { get; set; }
        ///// <summary>
        ///// 
        ///// </summary>
        //public virtual ICollection<ESM_ORDER_LIMIT> ESM_ORDER_LIMIT { get; set; }
        ///// <summary>
        ///// 
        ///// </summary>
        //public virtual ICollection<ESM_PART_BUYER_GROUP> ESM_PART_BUYER_GROUP { get; set; }
        ///// <summary>
        ///// 
        ///// </summary>
        //public virtual ICollection<ESM_PART> ESM_PART { get; set; }
        ///// <summary>
        ///// 
        ///// </summary>
        //public virtual ICollection<ESM_PART_PRICE_AGGREGATE> ESM_PART_PRICE_AGGREGATE { get; set; }
        ///// <summary>
        ///// 
        ///// </summary>
        //public virtual ICollection<ESM_PROJECTS> ESM_PROJECTS { get; set; }
        ///// <summary>
        ///// 
        ///// </summary>
        //public virtual ICollection<ESM_PROMO_COMPANY> ESM_PROMO_COMPANY { get; set; }
        ///// <summary>
        ///// 
        ///// </summary>
        //public virtual ICollection<ESM_PROMOTIONS> ESM_PROMOTIONS { get; set; }
        ///// <summary>
        ///// 
        ///// </summary>
        //public virtual ICollection<ESM_PURCHASE_ORDERS> ESM_PURCHASE_ORDERS { get; set; }
        ///// <summary>
        ///// 
        ///// </summary>
        //public virtual ICollection<ESM_REP_SLICE_SNAPSHOT> ESM_REP_SLICE_SNAPSHOT { get; set; }
        ///// <summary>
        ///// 
        ///// </summary>
        //public virtual ICollection<ESM_REPNEW_REPORT_SCHEDULER> ESM_REPNEW_REPORT_SCHEDULER { get; set; }
        ///// <summary>
        ///// 
        ///// </summary>
        //public virtual ICollection<ESM_REPNEW_VIEWS> ESM_REPNEW_VIEWS { get; set; }
        ///// <summary>
        ///// 
        ///// </summary>
        //public virtual ICollection<ESM_RET_PROJECT> ESM_RET_PROJECT { get; set; }
        ///// <summary>
        ///// 
        ///// </summary>
        //public virtual ICollection<ESM_RET_USER_GROUP> ESM_RET_USER_GROUP { get; set; }
        ///// <summary>
        ///// 
        ///// </summary>
        //public virtual ICollection<ESM_RMA> ESM_RMA { get; set; }
        ///// <summary>
        ///// 
        ///// </summary>
        //public virtual ICollection<ESM_SERVICE_SECURITY> ESM_SERVICE_SECURITY { get; set; }
        ///// <summary>
        ///// 
        ///// </summary>
        //public virtual ICollection<ESM_SOFT_PROOFING_TRANSACTION_LOG> ESM_SOFT_PROOFING_TRANSACTION_LOG { get; set; }
        ///// <summary>
        ///// 
        ///// </summary>
        //public virtual ICollection<ESM_TEMPLATE> ESM_TEMPLATE { get; set; }
        ///// <summary>
        ///// 
        ///// </summary>
        //public virtual ICollection<ESM_THEME> ESM_THEME1 { get; set; }
        ///// <summary>
        ///// 
        ///// </summary>
        //public virtual ICollection<ESM_UI_CUSTOM_TEXT> ESM_UI_CUSTOM_TEXT { get; set; }
        ///// <summary>
        ///// 
        ///// </summary>
        //public virtual ICollection<SYS_ALERT_OPTIONS> SYS_ALERT_OPTIONS { get; set; }
        ///// <summary>
        ///// 
        ///// </summary>
        //public virtual ICollection<SYS_TASK> SYS_TASK { get; set; }
        ///// <summary>
        ///// 
        ///// </summary>
        //public virtual ICollection<SYS_TASK_ORDER_IMPORT> SYS_TASK_ORDER_IMPORT { get; set; }
        ///// <summary>
        ///// 
        ///// </summary>
        //public virtual ICollection<ESM_COMPGROUP> ESM_COMPGROUP1 { get; set; }
        ///// <summary>
        ///// 
        ///// </summary>
        //public virtual ICollection<ESM_ORDERS> ESM_ORDERS { get; set; }
        ///// <summary>
        ///// 
        ///// </summary>
        //public virtual ICollection<ESM_COMPANY_PRICEBREAK_COST_FIELDS> ESM_COMPANY_PRICEBREAK_COST_FIELDS { get; set; }
    }
}
