//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArgosyModel
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    
    [DataContract]
    [Serializable]
    public partial class ESM_ORDERS
    {
        public ESM_ORDERS()
        {
            //this.ESM_APPROVALS = new HashSet<ESM_APPROVALS>();
            //this.ESM_COMP_USER_DOLLAR = new HashSet<ESM_COMP_USER_DOLLAR>();
            //this.ESM_ORDER_ADDRESS = new HashSet<ESM_ORDER_ADDRESS>();
            //this.ESM_ORDER_APPROVER_WORKFLOW = new HashSet<ESM_ORDER_APPROVER_WORKFLOW>();
            //this.ESM_ORDER_AVALARA_RESPONSE = new HashSet<ESM_ORDER_AVALARA_RESPONSE>();
            //this.ESM_ORDER_CUST_FIELDS = new HashSet<ESM_ORDER_CUST_FIELDS>();
            //this.ESM_ORDER_LINE = new HashSet<ESM_ORDER_LINE>();
            //this.ESM_ORDER_PRODUCER = new HashSet<ESM_ORDER_PRODUCER>();
            //this.ESM_ORDER_PROMO_APPLIED = new HashSet<ESM_ORDER_PROMO_APPLIED>();
            //this.ESM_ORDER_SHIPPER = new HashSet<ESM_ORDER_SHIPPER>();
            //this.ESM_ORDER_SHIPPER1 = new HashSet<ESM_ORDER_SHIPPER>();
            //this.ESM_PAYMENT_AUTH = new HashSet<ESM_PAYMENT_AUTH>();
            //this.ESM_PAYMENT_TRANSACTION = new HashSet<ESM_PAYMENT_TRANSACTION>();
            //this.ESM_RET_PROJECT1 = new HashSet<ESM_RET_PROJECT>();
            //this.ESM_RMA = new HashSet<ESM_RMA>();
            //this.ESM_WMS_TASKS = new HashSet<ESM_WMS_TASKS>();
            //this.SYS_TASK_ORDER_IMPORT = new HashSet<SYS_TASK_ORDER_IMPORT>();
            //this.ESM_INV_TRANS = new HashSet<ESM_INV_TRANS>();
            //this.ESM_ORDER_FILES = new HashSet<ESM_ORDER_FILES>();
        }
    	// primitiveProperties
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "ORDER_ID")]
        public int ORDER_ID { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "COMP_USER_ID")]
        public int COMP_USER_ID { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "COMPANY_ID")]
        public int COMPANY_ID { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "SITE_ID")]
        public int SITE_ID { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "TYPE_ID")]
        public int TYPE_ID { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "STATUS_ID")]
        public string STATUS_ID { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "CARRIER_ID")]
        public int CARRIER_ID { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "CONSOLIDATE_ID")]
        public Nullable<int> CONSOLIDATE_ID { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "RETAIL_PROJ_ID")]
        public Nullable<int> RETAIL_PROJ_ID { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "ACCOUNTING_UNIT_ID")]
        public Nullable<int> ACCOUNTING_UNIT_ID { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "ORDER_DISP_NO")]
        public string ORDER_DISP_NO { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "PO_NUM")]
        public string PO_NUM { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "ORDER_DATE")]
        public System.DateTime ORDER_DATE { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "CLOSE_DATE")]
        public Nullable<System.DateTime> CLOSE_DATE { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "PICK_DATE")]
        public Nullable<System.DateTime> PICK_DATE { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "DESIRED_SHIP_DATE")]
        public System.DateTime DESIRED_SHIP_DATE { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "INVOICE_DATE")]
        public System.DateTime INVOICE_DATE { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "CREDIT_CARD_INFO")]
        public string CREDIT_CARD_INFO { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "COMMENTS")]
        public string COMMENTS { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "EXPEDITE")]
        public bool EXPEDITE { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "PRICE_TYPE")]
        public string PRICE_TYPE { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "CZ")]
        public Nullable<int> CZ { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "PICKER")]
        public Nullable<int> PICKER { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "EST_SHIPPING_COSTS")]
        public decimal EST_SHIPPING_COSTS { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "FULFILL_ORDER_COST")]
        public decimal FULFILL_ORDER_COST { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "FULFILL_LINE_COST")]
        public decimal FULFILL_LINE_COST { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "FULFILL_EACH_COST")]
        public decimal FULFILL_EACH_COST { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "LIST_COST")]
        public decimal LIST_COST { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "DISCOUNT")]
        public decimal DISCOUNT { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "SALES_TAX_CHARGES")]
        public decimal SALES_TAX_CHARGES { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "THIRD_PARTY_ACCOUNT_NUMBER")]
        public string THIRD_PARTY_ACCOUNT_NUMBER { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "INVOICE_STATUS")]
        public int INVOICE_STATUS { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "CONSUMER_ID")]
        public Nullable<int> CONSUMER_ID { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "PAYMENT_IS_COMPLETE")]
        public bool PAYMENT_IS_COMPLETE { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "IS_INCOMPLETE_ORDER")]
        public bool IS_INCOMPLETE_ORDER { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "EMAIL_SENT")]
        public bool EMAIL_SENT { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "FLAG_CONSOLIDATED")]
        public Nullable<bool> FLAG_CONSOLIDATED { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "FLAG_ALLOW_PARTIAL_SHIP")]
        public Nullable<bool> FLAG_ALLOW_PARTIAL_SHIP { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "FLAG_ALLOW_CONSOLIDATE_ORDERS")]
        public bool FLAG_ALLOW_CONSOLIDATE_ORDERS { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "FLAG_REQUIRE_CARTONS")]
        public Nullable<bool> FLAG_REQUIRE_CARTONS { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "IS_FREIGHT_ONLY_BILLING")]
        public bool IS_FREIGHT_ONLY_BILLING { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "IS_PAID_IN_FULL_AT_TIME_OF_ORDER")]
        public bool IS_PAID_IN_FULL_AT_TIME_OF_ORDER { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "FLAG_PAYMENT")]
        public string FLAG_PAYMENT { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "FAST_PICKPACK")]
        public bool FAST_PICKPACK { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "FLAG_REQUIRE_SIGNATURE")]
        public bool FLAG_REQUIRE_SIGNATURE { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "APPROVAL_WORK_FLOW_TYPE")]
        public string APPROVAL_WORK_FLOW_TYPE { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "EXEMPT_SHIPPING_AND_HANDLING")]
        public bool EXEMPT_SHIPPING_AND_HANDLING { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "SHIPPING_AND_HANDLING_PAID_BY_THIRD_PARTY")]
        public bool SHIPPING_AND_HANDLING_PAID_BY_THIRD_PARTY { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "CUSTOM01")]
        public string CUSTOM01 { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "CUSTOM02")]
        public string CUSTOM02 { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "CUSTOM03")]
        public string CUSTOM03 { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "CUSTOM04")]
        public string CUSTOM04 { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "CUSTOM05")]
        public string CUSTOM05 { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "DATECREATED")]
        public System.DateTime DATECREATED { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "CREATEDBY")]
        public int CREATEDBY { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "DATEMODIFIED")]
        public System.DateTime DATEMODIFIED { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "MODIFIEDBY")]
        public int MODIFIEDBY { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "APPROVE_DENY_DATE")]
        public Nullable<System.DateTime> APPROVE_DENY_DATE { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "WAREHOUSE_ID")]
        public Nullable<int> WAREHOUSE_ID { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "PROMO_CODE")]
        public string PROMO_CODE { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "PROMO_CODE_DISCOUNT")]
        public Nullable<decimal> PROMO_CODE_DISCOUNT { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "DESIRE_PROD_DATE")]
        public System.DateTime DESIRE_PROD_DATE { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "APPROVAL_PENDING_REASON")]
        public string APPROVAL_PENDING_REASON { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "ORDER_TAG")]
        public string ORDER_TAG { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "ORDER_WEIGHT")]
        public decimal ORDER_WEIGHT { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "ORDER_GUID")]
        public System.Guid ORDER_GUID { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "IS_TRANSMITTED")]
        public bool IS_TRANSMITTED { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "APPROVAL_SUMMARY")]
        public string APPROVAL_SUMMARY { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "CURRANCY_CODE")]
        public string CURRANCY_CODE { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "LANGUAGE_CULTURE")]
        public string LANGUAGE_CULTURE { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "CURRENCY_CODE")]
        public string CURRENCY_CODE { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "SHIPPING_ESTIMATE_CALC_JSON")]
        public string SHIPPING_ESTIMATE_CALC_JSON { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "INVOICE_FEE")]
        public Nullable<decimal> INVOICE_FEE { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "MAIL_INVOICE")]
        public bool MAIL_INVOICE { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "INVOICE_EMAIL")]
        public string INVOICE_EMAIL { get; set; }
    	// navigationProperty
    
        /// <summary>
        /// 
        /// </summary>
        //public virtual ESM_ACCOUNTING_UNIT ESM_ACCOUNTING_UNIT { get; set; }
        ///// <summary>
        ///// 
        ///// </summary>
        //[DataMember(Name = "ESM_APPROVALS")]
        //public virtual ICollection<ESM_APPROVALS> ESM_APPROVALS { get; set; }
        ///// <summary>
        ///// 
        ///// </summary>
        //[DataMember(Name = "ESM_CARRIERS")]
        //public virtual ESM_CARRIERS ESM_CARRIERS { get; set; }
        ///// <summary>
        ///// 
        ///// </summary>
        //public virtual ICollection<ESM_COMP_USER_DOLLAR> ESM_COMP_USER_DOLLAR { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "ESM_COMP_USERS")]
        public virtual ESM_COMP_USERS ESM_COMP_USERS { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "ESM_COMPANY")]
        public virtual ESM_COMPANY ESM_COMPANY { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "ESM_CONSUMER")]
        public virtual ESM_CONSUMER ESM_CONSUMER { get; set; }
        /// <summary>
        /// 
        /// </summary>
        //[DataMember(Name = "ESM_ORDER_ADDRESS")]
        //public virtual ICollection<ESM_ORDER_ADDRESS> ESM_ORDER_ADDRESS { get; set; }
        ///// <summary>
        ///// 
        ///// </summary>
        //public virtual ICollection<ESM_ORDER_APPROVER_WORKFLOW> ESM_ORDER_APPROVER_WORKFLOW { get; set; }
        ///// <summary>
        ///// 
        ///// </summary>
        //public virtual ICollection<ESM_ORDER_AVALARA_RESPONSE> ESM_ORDER_AVALARA_RESPONSE { get; set; }
        ///// <summary>
        ///// 
        ///// </summary>
        //[DataMember(Name = "ESM_ORDER_CUST_FIELDS")]
        //public virtual ICollection<ESM_ORDER_CUST_FIELDS> ESM_ORDER_CUST_FIELDS { get; set; }
        ///// <summary>
        ///// 
        ///// </summary>
        //[DataMember(Name = "ESM_ORDER_LINE")]
        //public virtual ICollection<ESM_ORDER_LINE> ESM_ORDER_LINE { get; set; }
        ///// <summary>
        ///// 
        ///// </summary>
        //public virtual ICollection<ESM_ORDER_PRODUCER> ESM_ORDER_PRODUCER { get; set; }
        ///// <summary>
        ///// 
        ///// </summary>
        //public virtual ICollection<ESM_ORDER_PROMO_APPLIED> ESM_ORDER_PROMO_APPLIED { get; set; }
        ///// <summary>
        ///// 
        ///// </summary>
        //[DataMember(Name = "ESM_ORDER_SHIPPER")]
        //public virtual ICollection<ESM_ORDER_SHIPPER> ESM_ORDER_SHIPPER { get; set; }
        ///// <summary>
        ///// 
        ///// </summary>
        //public virtual ICollection<ESM_ORDER_SHIPPER> ESM_ORDER_SHIPPER1 { get; set; }
        ///// <summary>
        ///// 
        ///// </summary>
        //[DataMember(Name = "ESM_ORDER_STATUS")]
        //public virtual ESM_ORDER_STATUS ESM_ORDER_STATUS { get; set; }
        ///// <summary>
        ///// 
        ///// </summary>
        //public virtual ESM_ORDER_TYPE ESM_ORDER_TYPE { get; set; }
        ///// <summary>
        ///// 
        ///// </summary>
        //public virtual ESM_RET_PROJECT ESM_RET_PROJECT { get; set; }
        ///// <summary>
        ///// 
        ///// </summary>
        //public virtual ESM_SITE ESM_SITE { get; set; }
        ///// <summary>
        ///// 
        ///// </summary>
        //public virtual ESM_SITE_LOCATIONS ESM_SITE_LOCATIONS { get; set; }
        ///// <summary>
        ///// 
        ///// </summary>
        //public virtual ESM_WAREHOUSE ESM_WAREHOUSE { get; set; }
        ///// <summary>
        ///// 
        ///// </summary>
        //[DataMember(Name = "ESM_PAYMENT_AUTH")]
        //public virtual ICollection<ESM_PAYMENT_AUTH> ESM_PAYMENT_AUTH { get; set; }
        ///// <summary>
        ///// 
        ///// </summary>
        //public virtual ICollection<ESM_PAYMENT_TRANSACTION> ESM_PAYMENT_TRANSACTION { get; set; }
        ///// <summary>
        ///// 
        ///// </summary>
        //public virtual ICollection<ESM_RET_PROJECT> ESM_RET_PROJECT1 { get; set; }
        ///// <summary>
        ///// 
        ///// </summary>
        //public virtual ICollection<ESM_RMA> ESM_RMA { get; set; }
        /// <summary>
        /// 
        /// </summary>
        //public virtual ICollection<ESM_WMS_TASKS> ESM_WMS_TASKS { get; set; }
        ///// <summary>
        ///// 
        ///// </summary>
        //public virtual ICollection<SYS_TASK_ORDER_IMPORT> SYS_TASK_ORDER_IMPORT { get; set; }
        ///// <summary>
        ///// 
        ///// </summary>
        //public virtual ICollection<ESM_INV_TRANS> ESM_INV_TRANS { get; set; }
        ///// <summary>
        ///// 
        ///// </summary>
        //public virtual ICollection<ESM_ORDER_FILES> ESM_ORDER_FILES { get; set; }
    }
}
