//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArgosyModel
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    
    [DataContract]
    [Serializable]
    public partial class ESM_SITE
    {
        public ESM_SITE()
        {
            //this.ESM_BATCH = new HashSet<ESM_BATCH>();
            //this.ESM_CARRIER_USERGROUP = new HashSet<ESM_CARRIER_USERGROUP>();
            //this.ESM_CARRIERS = new HashSet<ESM_CARRIERS>();
            //this.ESM_COMP_CONTACT = new HashSet<ESM_COMP_CONTACT>();
            //this.ESM_COMP_PRICELIST = new HashSet<ESM_COMP_PRICELIST>();
            //this.ESM_COMP_USERS = new HashSet<ESM_COMP_USERS>();
            //this.ESM_CONSUMER_COMPANY = new HashSet<ESM_CONSUMER_COMPANY>();
            //this.ESM_CUSTOMIZATION_TEMPLATE = new HashSet<ESM_CUSTOMIZATION_TEMPLATE>();
            //this.ESM_HD_TICKET = new HashSet<ESM_HD_TICKET>();
            //this.ESM_IMPORT_PROCESSING = new HashSet<ESM_IMPORT_PROCESSING>();
            //this.ESM_INV_ADJUSTMENT_APPROVAL = new HashSet<ESM_INV_ADJUSTMENT_APPROVAL>();
            //this.ESM_JOB = new HashSet<ESM_JOB>();
            //this.ESM_MESSAGES = new HashSet<ESM_MESSAGES>();
            //this.ESM_ORDER_SHIPPER = new HashSet<ESM_ORDER_SHIPPER>();
            //this.ESM_PAPER_STOCK = new HashSet<ESM_PAPER_STOCK>();
            //this.ESM_PAPER_STOCK_ATTRIBUTES = new HashSet<ESM_PAPER_STOCK_ATTRIBUTES>();
            //this.ESM_PART = new HashSet<ESM_PART>();
            //this.ESM_PART_CONFIG_TYPE = new HashSet<ESM_PART_CONFIG_TYPE>();
            //this.ESM_PRODUCTION_QUEUE = new HashSet<ESM_PRODUCTION_QUEUE>();
            //this.ESM_PURCHASE_ORDERS = new HashSet<ESM_PURCHASE_ORDERS>();
            //this.ESM_REP_SLICE_SNAPSHOT = new HashSet<ESM_REP_SLICE_SNAPSHOT>();
            //this.ESM_REPNEW_REPORT_SCHEDULER = new HashSet<ESM_REPNEW_REPORT_SCHEDULER>();
            //this.ESM_REPNEW_VIEWS = new HashSet<ESM_REPNEW_VIEWS>();
            //this.ESM_RMA = new HashSet<ESM_RMA>();
            //this.ESM_SERVICE_SECURITY = new HashSet<ESM_SERVICE_SECURITY>();
            //this.ESM_SITE_PART_LOCATION = new HashSet<ESM_SITE_PART_LOCATION>();
            //this.ESM_SITE_LICENSES = new HashSet<ESM_SITE_LICENSES>();
            //this.ESM_SITE_ALLOWED_CREDIT_CARD_TYPE = new HashSet<ESM_SITE_ALLOWED_CREDIT_CARD_TYPE>();
            //this.ESM_SITE_CONNECTORS = new HashSet<ESM_SITE_CONNECTORS>();
            //this.ESM_SITE_LICENSES1 = new HashSet<ESM_SITE_LICENSES>();
            //this.ESM_SITE_LOCATIONS = new HashSet<ESM_SITE_LOCATIONS>();
            //this.ESM_SOFT_PROOFING_DDL_GLOBAL_DATA_SOURCE_ID = new HashSet<ESM_SOFT_PROOFING_DDL_GLOBAL_DATA_SOURCE_ID>();
            //this.ESM_SOFT_PROOFING_PROJECT = new HashSet<ESM_SOFT_PROOFING_PROJECT>();
            //this.ESM_TEMPLATE = new HashSet<ESM_TEMPLATE>();
            //this.ESM_USERS = new HashSet<ESM_USERS>();
            //this.ESM_WAREHOUSE = new HashSet<ESM_WAREHOUSE>();
            //this.MULTIPLIERS = new HashSet<MULTIPLIER>();
            //this.SYS_SHIP_COMPLETE = new HashSet<SYS_SHIP_COMPLETE>();
            //this.SYS_SHIP_PENDING = new HashSet<SYS_SHIP_PENDING>();
            //this.SYS_SITE_BILLING = new HashSet<SYS_SITE_BILLING>();
            //this.SYS_SITE_SUMMARY = new HashSet<SYS_SITE_SUMMARY>();
            //this.SYS_TASK = new HashSet<SYS_TASK>();
            //this.SYS_TASK_ORDER_IMPORT = new HashSet<SYS_TASK_ORDER_IMPORT>();
            //this.SYS_SITE_LIC_PLAN = new HashSet<SYS_SITE_LIC_PLAN>();
            //this.ESM_SITE_GATEWAY = new HashSet<ESM_SITE_GATEWAY>();
            //this.ESM_SOFT_PROOFING_TRANSACTION_LOG = new HashSet<ESM_SOFT_PROOFING_TRANSACTION_LOG>();
            //this.ESM_COMPANY_PAGE = new HashSet<ESM_COMPANY_PAGE>();
            //this.ESM_ORDER_PRODUCER = new HashSet<ESM_ORDER_PRODUCER>();
            //this.ESM_ORDER_SHIPPER_PRODUCER = new HashSet<ESM_ORDER_SHIPPER_PRODUCER>();
            //this.ESM_SITE_PRODUCER = new HashSet<ESM_SITE_PRODUCER>();
            //this.ESM_SITE_PRODUCER1 = new HashSet<ESM_SITE_PRODUCER>();
            //this.ESM_PROMOTIONS = new HashSet<ESM_PROMOTIONS>();
            //this.ESM_DYNAMIC_DATASOURCE = new HashSet<ESM_DYNAMIC_DATASOURCE>();
            //this.SYS_ALERT_OPTIONS = new HashSet<SYS_ALERT_OPTIONS>();
            //this.ESM_DISCOUNT = new HashSet<ESM_DISCOUNT>();
            //this.ESM_PART_PRODUCER = new HashSet<ESM_PART_PRODUCER>();
            //this.ESM_CXML_CONFIG = new HashSet<ESM_CXML_CONFIG>();
            //this.ESM_USERS_SITE_ACCESS = new HashSet<ESM_USERS_SITE_ACCESS>();
            //this.ESM_SITE_DOMAIN = new HashSet<ESM_SITE_DOMAIN>();
            //this.ESM_STATEMENT = new HashSet<ESM_STATEMENT>();
            //this.ESM_STATEMENT_GROUPS = new HashSet<ESM_STATEMENT_GROUPS>();
            //this.ESM_PAYMENT_AUTH = new HashSet<ESM_PAYMENT_AUTH>();
            //this.ESM_THEME = new HashSet<ESM_THEME>();
            //this.ESM_PAYMENT_TRANSACTION = new HashSet<ESM_PAYMENT_TRANSACTION>();
            //this.ESM_LOCALIZATION = new HashSet<ESM_LOCALIZATION>();
            //this.ESM_PART_ATTRIBUTES_TYPE = new HashSet<ESM_PART_ATTRIBUTES_TYPE>();
            //this.ESM_COMP_USER_DOLLAR_BUCKET = new HashSet<ESM_COMP_USER_DOLLAR_BUCKET>();
            //this.ESM_ORDER_LINE = new HashSet<ESM_ORDER_LINE>();
            //this.ESM_SITE_SHIPMENT_GROUP = new HashSet<ESM_SITE_SHIPMENT_GROUP>();
            //this.ESM_VENDOR = new HashSet<ESM_VENDOR>();
            //this.ESM_BOX_SIZE = new HashSet<ESM_BOX_SIZE>();
            //this.ESM_DATA_PROVIDER_CONFIG = new HashSet<ESM_DATA_PROVIDER_CONFIG>();
            //this.ESM_SITE_UNIT_OF_MEASURE = new HashSet<ESM_SITE_UNIT_OF_MEASURE>();
            //this.ESM_COMPANY = new HashSet<ESM_COMPANY>();
            //this.ESM_COMPANY1 = new HashSet<ESM_COMPANY>();
            //this.ESM_CUSTOM_EMAIL = new HashSet<ESM_CUSTOM_EMAIL>();
            //this.ESM_ORDERS = new HashSet<ESM_ORDERS>();
            //this.ESM_INV_TRANS = new HashSet<ESM_INV_TRANS>();
            //this.ESM_INV_TRANS1 = new HashSet<ESM_INV_TRANS>();
            //this.SYS_INVENTORY_UPDATE = new HashSet<SYS_INVENTORY_UPDATE>();
            //this.ESM_MAILING_REQUEST = new HashSet<ESM_MAILING_REQUEST>();
        }
    	// primitiveProperties
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "SITE_ID")]
        public int SITE_ID { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "MP_ID")]
        public Nullable<int> MP_ID { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "PAYMENT_GATEWAY_ID")]
        public Nullable<int> PAYMENT_GATEWAY_ID { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "SITE_COMPANY")]
        public string SITE_COMPANY { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "CC_SITENAME")]
        public string CC_SITENAME { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "IMG_FILENAME")]
        public string IMG_FILENAME { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "UPLOAD_DIR")]
        public string UPLOAD_DIR { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "REPORT_CODE")]
        public string REPORT_CODE { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "FLAG_ARGOSY_WMS")]
        public string FLAG_ARGOSY_WMS { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "FLAG_ADDRESS_VERIFICATION")]
        public bool FLAG_ADDRESS_VERIFICATION { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "SHIP_FROM_CONTACT")]
        public string SHIP_FROM_CONTACT { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "SHIP_FROM_ADDRESS1")]
        public string SHIP_FROM_ADDRESS1 { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "SHIP_FROM_ADDRESS2")]
        public string SHIP_FROM_ADDRESS2 { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "SHIP_FROM_CITY")]
        public string SHIP_FROM_CITY { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "SHIP_FROM_STATE")]
        public Nullable<int> SHIP_FROM_STATE { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "SHIP_FROM_ZIP")]
        public string SHIP_FROM_ZIP { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "SHIP_FROM_COUNTRY")]
        public string SHIP_FROM_COUNTRY { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "SHIP_FROM_PHONE")]
        public string SHIP_FROM_PHONE { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "SHIP_FROM_FAX")]
        public string SHIP_FROM_FAX { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "MINMAX_EMAIL")]
        public string MINMAX_EMAIL { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "VS_USER")]
        public string VS_USER { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "VS_PARTNER")]
        public string VS_PARTNER { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "VS_VENDOR")]
        public string VS_VENDOR { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "VS_PWD")]
        public string VS_PWD { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "VS_LIVE_SERVER")]
        public bool VS_LIVE_SERVER { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "FLAG_RFQ_MODULE")]
        public string FLAG_RFQ_MODULE { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "VIRTUAL_DIRECTORY")]
        public string VIRTUAL_DIRECTORY { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "AMTREX_LOGIN")]
        public string AMTREX_LOGIN { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "DATECREATED")]
        public System.DateTime DATECREATED { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "CREATEDBY")]
        public int CREATEDBY { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "DATEMODIFIED")]
        public System.DateTime DATEMODIFIED { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "MODIFIEDBY")]
        public int MODIFIEDBY { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "ORDER_MID_NUM")]
        public Nullable<int> ORDER_MID_NUM { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "PHONE")]
        public string PHONE { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "VERSION")]
        public int VERSION { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "SOFTPROOFING_FTP_SITE")]
        public string SOFTPROOFING_FTP_SITE { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "BATCH_PROCESSING_FOLDER")]
        public string BATCH_PROCESSING_FOLDER { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "FLAT_RATE_CARRIER")]
        public bool FLAT_RATE_CARRIER { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "SITE_CC_CHARGE_NAME")]
        public string SITE_CC_CHARGE_NAME { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "INSTATE_TAX_RATE")]
        public Nullable<double> INSTATE_TAX_RATE { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "IS_ACTIVE")]
        public bool IS_ACTIVE { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "BATCH_SITE_CONNECTOR_ID")]
        public Nullable<int> BATCH_SITE_CONNECTOR_ID { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "SITE_URL")]
        public string SITE_URL { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "SITE_LABEL")]
        public string SITE_LABEL { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "SITE_SQUARE_LOGO")]
        public string SITE_SQUARE_LOGO { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "GUID")]
        public System.Guid GUID { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "FAVORITE_ICON_FILE")]
        public string FAVORITE_ICON_FILE { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "LOADING_IMAGE_FILE")]
        public string LOADING_IMAGE_FILE { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "FLAG_ALLOW_COMPANY_WHITE_LABEL")]
        public bool FLAG_ALLOW_COMPANY_WHITE_LABEL { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataMember(Name = "FLAG_TRACK_INVENTORY_COST")]
        public bool FLAG_TRACK_INVENTORY_COST { get; set; }
    	// navigationProperty
    
        /// <summary>
        /// 
        /// </summary>
        //public virtual ICollection<ESM_BATCH> ESM_BATCH { get; set; }
        ///// <summary>
        ///// 
        ///// </summary>
        //public virtual ICollection<ESM_CARRIER_USERGROUP> ESM_CARRIER_USERGROUP { get; set; }
        ///// <summary>
        ///// 
        ///// </summary>
        //public virtual ICollection<ESM_CARRIERS> ESM_CARRIERS { get; set; }
        ///// <summary>
        ///// 
        ///// </summary>
        //public virtual ICollection<ESM_COMP_CONTACT> ESM_COMP_CONTACT { get; set; }
        ///// <summary>
        ///// 
        ///// </summary>
        //public virtual ICollection<ESM_COMP_PRICELIST> ESM_COMP_PRICELIST { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public virtual ICollection<ESM_COMP_USERS> ESM_COMP_USERS { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public virtual ICollection<ESM_CONSUMER_COMPANY> ESM_CONSUMER_COMPANY { get; set; }
        /// <summary>
        /// 
        /// </summary>
        //public virtual ICollection<ESM_CUSTOMIZATION_TEMPLATE> ESM_CUSTOMIZATION_TEMPLATE { get; set; }
        ///// <summary>
        ///// 
        ///// </summary>
        //public virtual ICollection<ESM_HD_TICKET> ESM_HD_TICKET { get; set; }
        ///// <summary>
        ///// 
        ///// </summary>
        //public virtual ICollection<ESM_IMPORT_PROCESSING> ESM_IMPORT_PROCESSING { get; set; }
        ///// <summary>
        ///// 
        ///// </summary>
        //public virtual ICollection<ESM_INV_ADJUSTMENT_APPROVAL> ESM_INV_ADJUSTMENT_APPROVAL { get; set; }
        ///// <summary>
        ///// 
        ///// </summary>
        //public virtual ICollection<ESM_JOB> ESM_JOB { get; set; }
        ///// <summary>
        ///// 
        ///// </summary>
        //public virtual ICollection<ESM_MESSAGES> ESM_MESSAGES { get; set; }
        ///// <summary>
        ///// 
        ///// </summary>
        //public virtual ICollection<ESM_ORDER_SHIPPER> ESM_ORDER_SHIPPER { get; set; }
        ///// <summary>
        ///// 
        ///// </summary>
        //public virtual ICollection<ESM_PAPER_STOCK> ESM_PAPER_STOCK { get; set; }
        ///// <summary>
        ///// 
        ///// </summary>
        //public virtual ICollection<ESM_PAPER_STOCK_ATTRIBUTES> ESM_PAPER_STOCK_ATTRIBUTES { get; set; }
        ///// <summary>
        ///// 
        ///// </summary>
        //public virtual ICollection<ESM_PART> ESM_PART { get; set; }
        ///// <summary>
        ///// 
        ///// </summary>
        //public virtual ICollection<ESM_PART_CONFIG_TYPE> ESM_PART_CONFIG_TYPE { get; set; }
        ///// <summary>
        ///// 
        ///// </summary>
        //public virtual ESM_PAYMENT_GATEWAY ESM_PAYMENT_GATEWAY { get; set; }
        ///// <summary>
        ///// 
        ///// </summary>
        //public virtual ICollection<ESM_PRODUCTION_QUEUE> ESM_PRODUCTION_QUEUE { get; set; }
        ///// <summary>
        ///// 
        ///// </summary>
        //public virtual ICollection<ESM_PURCHASE_ORDERS> ESM_PURCHASE_ORDERS { get; set; }
        ///// <summary>
        ///// 
        ///// </summary>
        //public virtual ICollection<ESM_REP_SLICE_SNAPSHOT> ESM_REP_SLICE_SNAPSHOT { get; set; }
        ///// <summary>
        ///// 
        ///// </summary>
        //public virtual ICollection<ESM_REPNEW_REPORT_SCHEDULER> ESM_REPNEW_REPORT_SCHEDULER { get; set; }
        ///// <summary>
        ///// 
        ///// </summary>
        //public virtual ICollection<ESM_REPNEW_VIEWS> ESM_REPNEW_VIEWS { get; set; }
        ///// <summary>
        ///// 
        ///// </summary>
        //public virtual ICollection<ESM_RMA> ESM_RMA { get; set; }
        ///// <summary>
        ///// 
        ///// </summary>
        //public virtual ICollection<ESM_SERVICE_SECURITY> ESM_SERVICE_SECURITY { get; set; }
        ///// <summary>
        ///// 
        ///// </summary>
        //public virtual ESM_STATES ESM_STATES { get; set; }
        ///// <summary>
        ///// 
        ///// </summary>
        //public virtual ICollection<ESM_SITE_PART_LOCATION> ESM_SITE_PART_LOCATION { get; set; }
        ///// <summary>
        ///// 
        ///// </summary>
        //public virtual ICollection<ESM_SITE_LICENSES> ESM_SITE_LICENSES { get; set; }
        ///// <summary>
        ///// 
        ///// </summary>
        //public virtual ICollection<ESM_SITE_ALLOWED_CREDIT_CARD_TYPE> ESM_SITE_ALLOWED_CREDIT_CARD_TYPE { get; set; }
        ///// <summary>
        ///// 
        ///// </summary>
        //public virtual ICollection<ESM_SITE_CONNECTORS> ESM_SITE_CONNECTORS { get; set; }
        ///// <summary>
        ///// 
        ///// </summary>
        //public virtual ESM_SITE_CONNECTORS ESM_SITE_CONNECTORS1 { get; set; }
        ///// <summary>
        ///// 
        ///// </summary>
        //public virtual ICollection<ESM_SITE_LICENSES> ESM_SITE_LICENSES1 { get; set; }
        ///// <summary>
        ///// 
        ///// </summary>
        //public virtual ICollection<ESM_SITE_LOCATIONS> ESM_SITE_LOCATIONS { get; set; }
        ///// <summary>
        ///// 
        ///// </summary>
        //public virtual ICollection<ESM_SOFT_PROOFING_DDL_GLOBAL_DATA_SOURCE_ID> ESM_SOFT_PROOFING_DDL_GLOBAL_DATA_SOURCE_ID { get; set; }
        ///// <summary>
        ///// 
        ///// </summary>
        //public virtual ICollection<ESM_SOFT_PROOFING_PROJECT> ESM_SOFT_PROOFING_PROJECT { get; set; }
        ///// <summary>
        ///// 
        ///// </summary>
        //public virtual ICollection<ESM_TEMPLATE> ESM_TEMPLATE { get; set; }
        ///// <summary>
        ///// 
        ///// </summary>
        //public virtual ICollection<ESM_USERS> ESM_USERS { get; set; }
        ///// <summary>
        ///// 
        ///// </summary>
        //public virtual ICollection<ESM_WAREHOUSE> ESM_WAREHOUSE { get; set; }
        ///// <summary>
        ///// 
        ///// </summary>
        //public virtual ICollection<MULTIPLIER> MULTIPLIERS { get; set; }
        ///// <summary>
        ///// 
        ///// </summary>
        //public virtual ICollection<SYS_SHIP_COMPLETE> SYS_SHIP_COMPLETE { get; set; }
        ///// <summary>
        ///// 
        ///// </summary>
        //public virtual ICollection<SYS_SHIP_PENDING> SYS_SHIP_PENDING { get; set; }
        ///// <summary>
        ///// 
        ///// </summary>
        //public virtual ICollection<SYS_SITE_BILLING> SYS_SITE_BILLING { get; set; }
        ///// <summary>
        ///// 
        ///// </summary>
        //public virtual ICollection<SYS_SITE_SUMMARY> SYS_SITE_SUMMARY { get; set; }
        ///// <summary>
        ///// 
        ///// </summary>
        //public virtual ICollection<SYS_TASK> SYS_TASK { get; set; }
        ///// <summary>
        ///// 
        ///// </summary>
        //public virtual ICollection<SYS_TASK_ORDER_IMPORT> SYS_TASK_ORDER_IMPORT { get; set; }
        ///// <summary>
        ///// 
        ///// </summary>
        //public virtual ESM_SITE_MARKETPLACE ESM_SITE_MARKETPLACE { get; set; }
        ///// <summary>
        ///// 
        ///// </summary>
        //public virtual ICollection<SYS_SITE_LIC_PLAN> SYS_SITE_LIC_PLAN { get; set; }
        ///// <summary>
        ///// 
        ///// </summary>
        //public virtual ICollection<ESM_SITE_GATEWAY> ESM_SITE_GATEWAY { get; set; }
        ///// <summary>
        ///// 
        ///// </summary>
        //public virtual ICollection<ESM_SOFT_PROOFING_TRANSACTION_LOG> ESM_SOFT_PROOFING_TRANSACTION_LOG { get; set; }
        ///// <summary>
        ///// 
        ///// </summary>
        //public virtual ICollection<ESM_COMPANY_PAGE> ESM_COMPANY_PAGE { get; set; }
        ///// <summary>
        ///// 
        ///// </summary>
        //public virtual ICollection<ESM_ORDER_PRODUCER> ESM_ORDER_PRODUCER { get; set; }
        ///// <summary>
        ///// 
        ///// </summary>
        //public virtual ICollection<ESM_ORDER_SHIPPER_PRODUCER> ESM_ORDER_SHIPPER_PRODUCER { get; set; }
        ///// <summary>
        ///// 
        ///// </summary>
        //public virtual ICollection<ESM_SITE_PRODUCER> ESM_SITE_PRODUCER { get; set; }
        ///// <summary>
        ///// 
        ///// </summary>
        //public virtual ICollection<ESM_SITE_PRODUCER> ESM_SITE_PRODUCER1 { get; set; }
        ///// <summary>
        ///// 
        ///// </summary>
        //public virtual ICollection<ESM_PROMOTIONS> ESM_PROMOTIONS { get; set; }
        ///// <summary>
        ///// 
        ///// </summary>
        //public virtual ICollection<ESM_DYNAMIC_DATASOURCE> ESM_DYNAMIC_DATASOURCE { get; set; }
        ///// <summary>
        ///// 
        ///// </summary>
        //public virtual ICollection<SYS_ALERT_OPTIONS> SYS_ALERT_OPTIONS { get; set; }
        ///// <summary>
        ///// 
        ///// </summary>
        //public virtual ICollection<ESM_DISCOUNT> ESM_DISCOUNT { get; set; }
        ///// <summary>
        ///// 
        ///// </summary>
        //public virtual ICollection<ESM_PART_PRODUCER> ESM_PART_PRODUCER { get; set; }
        ///// <summary>
        ///// 
        ///// </summary>
        //public virtual ICollection<ESM_CXML_CONFIG> ESM_CXML_CONFIG { get; set; }
        ///// <summary>
        ///// 
        ///// </summary>
        //public virtual ICollection<ESM_USERS_SITE_ACCESS> ESM_USERS_SITE_ACCESS { get; set; }
        ///// <summary>
        ///// 
        ///// </summary>
        //public virtual ICollection<ESM_SITE_DOMAIN> ESM_SITE_DOMAIN { get; set; }
        ///// <summary>
        ///// 
        ///// </summary>
        //public virtual ICollection<ESM_STATEMENT> ESM_STATEMENT { get; set; }
        ///// <summary>
        ///// 
        ///// </summary>
        //public virtual ICollection<ESM_STATEMENT_GROUPS> ESM_STATEMENT_GROUPS { get; set; }
        ///// <summary>
        ///// 
        ///// </summary>
        //public virtual ICollection<ESM_PAYMENT_AUTH> ESM_PAYMENT_AUTH { get; set; }
        ///// <summary>
        ///// 
        /// </summary>
        public virtual ICollection<ESM_THEME> ESM_THEME { get; set; }
        /// <summary>
        /// 
        /// </summary>
        //public virtual ICollection<ESM_PAYMENT_TRANSACTION> ESM_PAYMENT_TRANSACTION { get; set; }
        ///// <summary>
        ///// 
        ///// </summary>
        //public virtual ICollection<ESM_LOCALIZATION> ESM_LOCALIZATION { get; set; }
        ///// <summary>
        ///// 
        ///// </summary>
        //public virtual ICollection<ESM_PART_ATTRIBUTES_TYPE> ESM_PART_ATTRIBUTES_TYPE { get; set; }
        ///// <summary>
        ///// 
        ///// </summary>
        //public virtual ICollection<ESM_COMP_USER_DOLLAR_BUCKET> ESM_COMP_USER_DOLLAR_BUCKET { get; set; }
        ///// <summary>
        ///// 
        ///// </summary>
        //public virtual ICollection<ESM_ORDER_LINE> ESM_ORDER_LINE { get; set; }
        /// <summary>
        /// 
        /// </summary>
        //public virtual ICollection<ESM_SITE_SHIPMENT_GROUP> ESM_SITE_SHIPMENT_GROUP { get; set; }
        ///// <summary>
        ///// 
        ///// </summary>
        //public virtual ICollection<ESM_VENDOR> ESM_VENDOR { get; set; }
        ///// <summary>
        ///// 
        ///// </summary>
        //public virtual ICollection<ESM_BOX_SIZE> ESM_BOX_SIZE { get; set; }
        ///// <summary>
        ///// 
        ///// </summary>
        //public virtual ICollection<ESM_DATA_PROVIDER_CONFIG> ESM_DATA_PROVIDER_CONFIG { get; set; }
        ///// <summary>
        ///// 
        ///// </summary>
        //public virtual ICollection<ESM_SITE_UNIT_OF_MEASURE> ESM_SITE_UNIT_OF_MEASURE { get; set; }
        ///// <summary>
        /// 
        /// </summary>
        public virtual ICollection<ESM_COMPANY> ESM_COMPANY { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public virtual ICollection<ESM_COMPANY> ESM_COMPANY1 { get; set; }
        /// <summary>
        /// 
        /// </summary>
        //public virtual ICollection<ESM_CUSTOM_EMAIL> ESM_CUSTOM_EMAIL { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public virtual ICollection<ESM_ORDERS> ESM_ORDERS { get; set; }
        /// <summary>
        /// 
        /// </summary>
        //public virtual ICollection<ESM_INV_TRANS> ESM_INV_TRANS { get; set; }
        ///// <summary>
        ///// 
        ///// </summary>
        //public virtual ICollection<ESM_INV_TRANS> ESM_INV_TRANS1 { get; set; }
        ///// <summary>
        ///// 
        ///// </summary>
        //public virtual ICollection<SYS_INVENTORY_UPDATE> SYS_INVENTORY_UPDATE { get; set; }
        ///// <summary>
        ///// 
        ///// </summary>
        //public virtual ICollection<ESM_MAILING_REQUEST> ESM_MAILING_REQUEST { get; set; }
    }
}
